name: Build Manuscript

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install latex
        run: sudo apt install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra
      - name: Install Rxiv-Maker
        run: pipx install rxiv-maker
      - name: Test rxiv maker
        run: rxiv check-installation
      - name: Build PDF
        run: rxiv pdf
      - name: Upload PDF
        uses: actions/upload-artifact@v7
        with:
          name: manuscript
          path: output/manuscript.pdf
